// Auto-generated by scripts/generate-icons.mjs from icons/AreaIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const AreaIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={12} height={17} fill="none" viewBox="0 0 12 17" {...props}><path stroke="currentcolor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={0.75} d="M8 9.187c1.766.347 3 1.14 3 2.063 0 1.243-2.239 2.25-5 2.25s-5-1.007-5-2.25c0-.923 1.234-1.716 3-2.063M6 11V4l2.659 1.636c.194.12.29.18.322.254a.25.25 0 0 1-.006.204c-.035.073-.136.127-.336.235L6 7.75" /></svg>;
export default AreaIcon;