// Auto-generated by scripts/generate-icons.mjs from icons/ArrowRightIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const ArrowRightIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={9} height={7} fill="none" viewBox="0 0 9 7" {...props}><path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" d="M.5 3.5h8m-3 3 3-3-3-3" /></svg>;
export default ArrowRightIcon;