// Auto-generated by scripts/generate-icons.mjs from icons/AvailableHeadingsIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const AvailableHeadingsIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={43} height={11} fill="none" viewBox="0 0 43 11" {...props}><path fill="#fff" stroke="#fff" strokeWidth={1.5} d="M5.5 10a4.5 4.5 0 1 0 0-9 4.5 4.5 0 0 0 0 9ZM21.25 10a4.5 4.5 0 1 0 0-9 4.5 4.5 0 0 0 0 9Z" /><path stroke="#fff" strokeWidth={1.5} d="M37 10a4.5 4.5 0 1 0 0-9 4.5 4.5 0 0 0 0 9Z" /></svg>;
export default AvailableHeadingsIcon;