// Auto-generated by scripts/generate-icons.mjs from icons/BackfillActivityIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const BackfillActivityIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={24} height={24} fill="none" stroke="currentcolor" viewBox="0 0 24 24" {...props}><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.75} d="M3 11v5.2c0 1.68 0 2.52.327 3.162a3 3 0 0 0 1.311 1.311C5.28 21 6.12 21 7.8 21h8.4c1.68 0 2.52 0 3.162-.327a3 3 0 0 0 1.311-1.311C21 18.72 21 17.88 21 16.2V11m-9-2 2.5-3.214M12 9 9.5 5.786M12 9V3M5.99 18h-.01m4 0H10m-2.01-2.9h-.01m6.01 2.9h.03M12 15.1h-.01M10 12.198h-.02m4.01 0h.03m-8.03 0h-.01M18.02 18h-.01m-1.99-2.9h-.01m2.01-2.901h-.01" /></svg>;
export default BackfillActivityIcon;