// Auto-generated by scripts/generate-icons.mjs from icons/BlastingIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const BlastingIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={24} height={24} fill="none" stroke="currentcolor" viewBox="0 0 24 24" {...props}><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.75} d="m2 12 .25.25M8 8 6 5m11-1-1 2.5m5.75 6.25.25-.25M7 20l-5-4 6.288-.032L5 10l5.15 2.697L12 4l2.422 9.06L20 9l-3.67 7.377L21 16l-4 4z" /></svg>;
export default BlastingIcon;