// Auto-generated by scripts/generate-icons.mjs from icons/BoreIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const BoreIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={40} height={40} fill="none" viewBox="0 0 40 40" {...props}><path stroke="currentcolor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M26.668 6.67H35m-10 5h11.666m-7.117 0v10.521m-16.585 8.024a3.118 3.118 0 0 1-6.236 0m6.236 0a3.12 3.12 0 0 0-3.118-3.117m3.118 3.117H19.2m-12.47 0a3.12 3.12 0 0 1 3.117-3.117m-3.118 3.117H3.334v-8.101h6.524m-.011 4.983.01-4.983m18.414 8.101a3.118 3.118 0 0 1-6.236 0m6.236 0a3.118 3.118 0 1 0-6.236 0m6.236 0h3.396l.217-4.967c.047-1.09-.824-2-1.915-2H19.2m2.835 6.967H19.2m-9.342-8.101-.011-4.535h6.247l3.106 5.669m0 0v6.967" /></svg>;
export default BoreIcon;