// Auto-generated by scripts/generate-icons.mjs from icons/BrokenStocksIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const BrokenStocksIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={24} height={24} fill="none" viewBox="0 0 24 24" {...props}><path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.75} d="M11.203 17.441 10.918 20l5.51-.095 2.376-2.37-2.565-1.99-3.169.096z" /><path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.75} d="m2 13.007.902-3.3 5.714-4.755L15.835 4 22 9.557l-5.414 2.85z" clipRule="evenodd" /></svg>;
export default BrokenStocksIcon;