// Auto-generated by scripts/generate-icons.mjs from icons/Calendar.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const Calendar = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={48} height={48} fill="none" viewBox="0 0 48 48" {...props}><path stroke="#D6D6D6" strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M42 20H6M32 4v8M16 4v8m-.4 32h16.8c3.36 0 5.04 0 6.324-.654a6 6 0 0 0 2.622-2.622C42 39.44 42 37.76 42 34.4V17.6c0-3.36 0-5.04-.654-6.324a6 6 0 0 0-2.622-2.622C37.44 8 35.76 8 32.4 8H15.6c-3.36 0-5.04 0-6.324.654a6 6 0 0 0-2.622 2.622C6 12.56 6 14.24 6 17.6v16.8c0 3.36 0 5.04.654 6.324a6 6 0 0 0 2.622 2.622C10.56 44 12.24 44 15.6 44" /></svg>;
export default Calendar;