// Auto-generated by scripts/generate-icons.mjs from icons/ChargingIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const ChargingIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={24} height={24} fill="none" stroke="currentcolor" viewBox="0 0 24 24" {...props}><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.75} d="M11.999 8h-2.5v3h5V8zm0 0V2m0 0h-5m5 0H17M5.5 11h13v11h-13z" /></svg>;
export default ChargingIcon;