// Auto-generated by scripts/generate-icons.mjs from icons/CheckIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const CheckIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={7} height={6} fill="none" viewBox="0 0 7 6" {...props}><path stroke="#000" strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M6.083.75 2.417 4.417.75 2.75" /></svg>;
export default CheckIcon;