// Auto-generated by scripts/generate-icons.mjs from icons/ChevronDownIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const ChevronDownIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={20} height={21} fill="none" stroke="#04203D" viewBox="0 0 20 21" {...props}><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="m5 8 5 5 5-5" /></svg>;
export default ChevronDownIcon;