// Auto-generated by scripts/generate-icons.mjs from icons/CleanIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const CleanIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={40} height={40} fill="none" viewBox="0 0 40 40" {...props}><path stroke="currentcolor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M20.024 3.333V19.39m0 0-7.801 1.73v3.888m7.801-5.618 7.754 1.73v3.888m-15.555 0L8.334 36.666h7.014m-3.125-11.658h15.555m0 0 3.89 11.658h-16.32m0 0 1.458-3.88" /></svg>;
export default CleanIcon;