// Auto-generated by scripts/generate-icons.mjs from icons/Clock.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const Clock = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={16} height={20} fill="none" viewBox="0 0 16 20" {...props}><path stroke="currentcolor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.25} d="M13.636 10.595a5.667 5.667 0 0 1-10.543 2.238l-.167-.288m-.562-3.14a5.667 5.667 0 0 1 10.543-2.238l.167.288M2.33 14.044l.488-1.821 1.821.488m6.724-5.422 1.82.488.489-1.821M8 7v3l1.667 1" /></svg>;
export default Clock;