// Auto-generated by scripts/generate-icons.mjs from icons/CommentEmptyIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const CommentEmptyIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={12} height={12} fill="none" viewBox="0 0 12 12" {...props}><path d="M1.5 3.9c0-.84 0-1.26.163-1.581a1.5 1.5 0 0 1 .656-.656c.32-.163.74-.163 1.581-.163h4.2c.84 0 1.26 0 1.581.163a1.5 1.5 0 0 1 .656.656c.163.32.163.74.163 1.581v2.7c0 .84 0 1.26-.164 1.581a1.5 1.5 0 0 1-.655.656C9.361 9 8.941 9 8.1 9H6.842c-.312 0-.468 0-.617.03a1.5 1.5 0 0 0-.381.134c-.136.07-.258.167-.501.362l-1.193.954c-.208.166-.312.25-.4.25a.25.25 0 0 1-.195-.094c-.055-.069-.055-.202-.055-.468V9c-.465 0-.697 0-.888-.051a1.5 1.5 0 0 1-1.06-1.06C1.5 7.696 1.5 7.464 1.5 7z" /></svg>;
export default CommentEmptyIcon;