// Auto-generated by scripts/generate-icons.mjs from icons/CommentIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const CommentIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={12} height={12} fill="none" viewBox="0 0 12 12" {...props}><path d="M5.5 2H3.9c-.84 0-1.26 0-1.581.163a1.5 1.5 0 0 0-.656.656c-.163.32-.163.74-.163 1.581V7c0 .465 0 .697.051.888a1.5 1.5 0 0 0 1.06 1.06C2.804 9 3.036 9 3.5 9v1.168c0 .266 0 .4.055.468a.25.25 0 0 0 .195.094c.088 0 .192-.084.4-.25l1.193-.954c.243-.195.365-.292.5-.362a1.5 1.5 0 0 1 .382-.133C6.374 9 6.53 9 6.842 9H7.6c.84 0 1.26 0 1.581-.163a1.5 1.5 0 0 0 .656-.656C10 7.861 10 7.441 10 6.6v-.1m.06-4.56A1.5 1.5 0 1 1 7.94 4.06a1.5 1.5 0 0 1 2.122-2.12" /></svg>;
export default CommentIcon;