// Auto-generated by scripts/generate-icons.mjs from icons/CrossIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const CrossIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={20} height={21} fill="none" stroke="currentColor" viewBox="0 0 20 21" {...props}><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="m14.167 6.333-8.334 8.334m0-8.334 8.334 8.334" /></svg>;
export default CrossIcon;