// Auto-generated by scripts/generate-icons.mjs from icons/CrusherIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const CrusherIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={36} height={28} fill="none" viewBox="220 30 40 32" {...props}><path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="m228.244 54.916-.011.004m25.023-9.125-.01.004m-12.496 4.556-.011.004m-16.404 5.982a4.17 4.17 0 0 1 2.486-5.34l25.013-9.121a4.16 4.16 0 0 1 5.331 2.49 4.17 4.17 0 0 1-2.486 5.34l-25.013 9.12a4.16 4.16 0 0 1-5.331-2.49m14.185-20.412-1.197 3.169 4.125 1.345 5.367-1.957-.856-4.956-3.677-1.113-1.368 3.683zm-4.535 7.383-.221-2.652-4.924-.845-1.398 3.157 2.44 1.837z" /></svg>;
export default CrusherIcon;