// Auto-generated by scripts/generate-icons.mjs from icons/DeleteIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const DeleteIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={20} height={20} fill="none" viewBox="0 0 20 20" {...props}><path stroke="#B8B8B8" strokeLinecap="round" strokeLinejoin="round" strokeWidth={0.75} d="M6 7.998a1 1 0 0 1-.98-.803C5 7.098 5 6.982 5 6.75s0-.348.02-.445a1 1 0 0 1 .785-.786c.097-.019.213-.019.445-.019h7.5c.232 0 .348 0 .445.02a1 1 0 0 1 .786.785c.019.097.019.213.019.445s0 .348-.02.445a1 1 0 0 1-.98.803M9 10.5h2M6 8h8v4.1c0 .84 0 1.26-.164 1.581a1.5 1.5 0 0 1-.655.656c-.32.163-.74.163-1.581.163H8.4c-.84 0-1.26 0-1.581-.164a1.5 1.5 0 0 1-.656-.655C6 13.361 6 12.941 6 12.1z" /></svg>;
export default DeleteIcon;