// Auto-generated by scripts/generate-icons.mjs from icons/DrillingIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const DrillingIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={24} height={24} fill="none" stroke="currentcolor" viewBox="0 0 24 24" {...props}><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.75} d="M16 5.066h5m-8.27 8.212h5M15 8.066h7m-4.27 0v6.711m-10.995 2.29a1.867 1.867 0 1 0-3.735 0m3.735 0a1.867 1.867 0 1 1-3.735 0m3.735 0h3.398m-7.133 0H2v-5.54l5.73-.75v-1.5h2.5l2.5 2v4.07m-2.597 1.72a1.868 1.868 0 0 1 2.597-1.72m-2.597 1.72a1.867 1.867 0 1 0 2.597-1.72" /></svg>;
export default DrillingIcon;