// Auto-generated by scripts/generate-icons.mjs from icons/EditIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const EditIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={16} height={17} fill="none" stroke="currentColor" viewBox="0 0 16 17" {...props}><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.25} d="M14 14.5H8.667m-7 .334 3.7-1.423a4 4 0 0 0 .465-.196q.148-.08.28-.182c.1-.077.189-.167.368-.346L14 5.167a1.886 1.886 0 1 0-2.667-2.666l-7.52 7.52c-.179.179-.268.268-.345.367q-.103.133-.183.28c-.059.111-.104.23-.195.466zm0 0 1.372-3.567c.098-.256.147-.383.231-.442a.33.33 0 0 1 .253-.053c.1.019.197.115.39.309l1.507 1.506c.193.193.29.29.309.39a.33.33 0 0 1-.054.253c-.058.085-.186.134-.441.232z" /></svg>;
export default EditIcon;