// Auto-generated by scripts/generate-icons.mjs from icons/EllipsisIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const EllipsisIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={16} height={20} fill="none" viewBox="0 0 16 20" {...props}><path stroke="#0D6DCF" strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.25} d="M8 10.667a.667.667 0 1 0 0-1.334.667.667 0 0 0 0 1.334M12.667 10.667a.667.667 0 1 0 0-1.334.667.667 0 0 0 0 1.334M3.333 10.667a.667.667 0 1 0 0-1.334.667.667 0 0 0 0 1.334" /></svg>;
export default EllipsisIcon;