// Auto-generated by scripts/generate-icons.mjs from icons/EncircledCrossIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const EncircledCrossIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={16} height={16} fill="none" viewBox="0 2 16 16" {...props}><path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.25} d="m10 8-4 4m0-4 4 4m4.667-2a6.667 6.667 0 1 1-13.334 0 6.667 6.667 0 0 1 13.334 0" /></svg>;
export default EncircledCrossIcon;