// Auto-generated by scripts/generate-icons.mjs from icons/EncircledExclamationIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const EncircledExclamationIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={16} height={17} fill="none" viewBox="0 0 16 17" {...props}><path stroke="#04203D" strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.75} d="M8 5.833V8.5m0 2.667h.007m6.66-2.667a6.667 6.667 0 1 1-13.334 0 6.667 6.667 0 0 1 13.334 0" /></svg>;
export default EncircledExclamationIcon;