// Auto-generated by scripts/generate-icons.mjs from icons/FacePrepIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const FacePrepIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={40} height={40} fill="none" viewBox="0 0 40 40" {...props}><path stroke="currentcolor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 5v5M6.666 35H10m3.333 0H10M30 5v5m0 25h-3.333m3.332 0h3.334M30 35V21.667M10 10H30m-20 0H5v11.667h4.999M30 10H35v11.667h-5M10 35V21.667m0 0h19.999M12.993 10 8.327 21.667M22.324 10l-4.666 11.667M31.655 10 26.99 21.667" /></svg>;
export default FacePrepIcon;