// Auto-generated by scripts/generate-icons.mjs from icons/FileIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const FileIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={18} height={22} fill="none" viewBox="0 0 18 22" {...props}><path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M10.75 1.02v4.13c0 .56 0 .84.109 1.054a1 1 0 0 0 .437.437c.214.11.494.11 1.054.11h4.13M5.75 14.75l2 2 4.5-4.5M10.75.75h-5.2c-1.68 0-2.52 0-3.162.327a3 3 0 0 0-1.311 1.311C.75 3.03.75 3.87.75 5.55v10.4c0 1.68 0 2.52.327 3.162a3 3 0 0 0 1.311 1.311c.642.327 1.482.327 3.162.327h6.4c1.68 0 2.52 0 3.162-.327a3 3 0 0 0 1.311-1.311c.327-.642.327-1.482.327-3.162v-9.2z" /></svg>;
export default FileIcon;