// Auto-generated by scripts/generate-icons.mjs from icons/FilledEncircledTickIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const FilledEncircledTickIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={21} height={20} fill="none" viewBox="0 0 21 20" {...props}><rect width={20} height={20} x={0.801} fill="#009462" rx={10} /><path stroke="#fff" strokeLinecap="round" strokeLinejoin="round" d="m14.801 7-5.5 5.5-2.5-2.5" /></svg>;
export default FilledEncircledTickIcon;