// Auto-generated by scripts/generate-icons.mjs from icons/FilledEncircledCrossIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const FilledEncircledCrossIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={21} height={20} fill="none" viewBox="0 0 21 20" {...props}><rect width={20} height={20} x={0.801} fill="#04203D" fillOpacity={0.24} rx={10} /><path stroke="#04203D" strokeLinecap="round" strokeLinejoin="round" d="m13.301 7.5-5 5m0-5 5 5" /></svg>;
export default FilledEncircledCrossIcon;