// Auto-generated by scripts/generate-icons.mjs from icons/Filter.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const Filter = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={20} height={20} fill="none" viewBox="0 0 20 20" {...props}><path stroke="#000" strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M2.822 4.722c-.63-.704-.946-1.056-.958-1.356a.83.83 0 0 1 .302-.675c.231-.191.704-.191 1.65-.191h12.368c.946 0 1.418 0 1.65.19.2.166.312.416.301.676-.012.3-.327.652-.957 1.356l-4.755 5.315c-.126.14-.189.21-.233.29a.8.8 0 0 0-.087.227c-.02.09-.02.184-.02.372v4.456c0 .163 0 .244-.026.315a.4.4 0 0 1-.11.163c-.056.05-.132.08-.283.141l-2.833 1.133c-.307.123-.46.184-.583.159a.42.42 0 0 1-.262-.178c-.07-.105-.07-.27-.07-.6v-5.589c0-.188 0-.283-.02-.372a.8.8 0 0 0-.086-.226 1.8 1.8 0 0 0-.233-.291z" /></svg>;
export default Filter;