// Auto-generated by scripts/generate-icons.mjs from icons/FolderIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const FolderIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={12} height={12} fill="none" viewBox="0 0 12 12" {...props}><g clipPath="url(#a)"><path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" d="m6.5 3.5-.558-1.116c-.16-.32-.24-.481-.36-.598a1 1 0 0 0-.374-.231C5.05 1.5 4.87 1.5 4.511 1.5H2.6c-.56 0-.84 0-1.054.109a1 1 0 0 0-.437.437C1 2.26 1 2.54 1 3.1v.4m0 0h7.6c.84 0 1.26 0 1.581.163a1.5 1.5 0 0 1 .656.656c.163.32.163.74.163 1.581v2.2c0 .84 0 1.26-.164 1.581a1.5 1.5 0 0 1-.655.656c-.32.163-.74.163-1.581.163H3.4c-.84 0-1.26 0-1.581-.164a1.5 1.5 0 0 1-.656-.655C1 9.361 1 8.941 1 8.1z" /></g><defs><clipPath id="a"><path fill="#fff" d="M0 0h12v12H0z" /></clipPath></defs></svg>;
export default FolderIcon;