// Auto-generated by scripts/generate-icons.mjs from icons/GeologyIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const GeologyIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={24} height={24} fill="none" viewBox="0 0 24 24" {...props}><path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M17.384 19.543h2.844L22 14.68l-3.293-8.434-4.787-1.789-5.063 2.19-2.666 5.756M22 14.68l-3.897 2.045M8.857 6.648l3.037 2.227 2.986 6.505 3.223 1.345M6.191 12.403l-1.962.981-.556 1.006m2.518-1.987h1.527l3.569 2.47.81 3.392-.988 1.278m6.994-2.818-.719 2.818m0 0H11.11m0 0H8.63M3.673 14.39l-.639 1.156c-.727 1.315-1.09 1.973-1.027 2.511.056.47.306.894.69 1.17.44.316 1.192.316 2.695.316h3.237M3.673 14.39l4.045 1.977.91 3.176" /></svg>;
export default GeologyIcon;