// Auto-generated by scripts/generate-icons.mjs from icons/Geology.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const Geology = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={24} height={24} fill="none" viewBox="0 0 24 24" {...props}><path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="m11.203 18.956-.285 2.565 5.51-.095 2.376-2.376-2.565-1.995-3.169.095z" /><path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="m2 14.51.902-3.309 5.714-6.767 7.219-1.955L22 11.051l-5.414 2.857z" clipRule="evenodd" /></svg>;
export default Geology;