// Auto-generated by scripts/generate-icons.mjs from icons/HaulTruckIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const HaulTruckIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={40} height={40} fill="none" viewBox="0 0 40 40" {...props}><path stroke="currentcolor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M31.667 7.5h-7.5m-9.166 20h10m-.834-20h-4.166l-1.762 3.333H5l-1.667 5 10 6.667h6.667zm.917 20q-.083.405-.083.833a4.167 4.167 0 1 0 8.25-.833m-8.167 0a4.168 4.168 0 0 1 8.167 0m-8.167 0h-.083m8.25 0h.083a3.333 3.333 0 0 0 3.333-3.333v-2.94a3.33 3.33 0 0 0-1.842-2.982l-1.491-.745-1.667-5h-6.666v15m-10 .833a4.167 4.167 0 1 1-8.334 0 4.167 4.167 0 0 1 8.334 0" /></svg>;
export default HaulTruckIcon;