// Auto-generated by scripts/generate-icons.mjs from icons/ImportIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const ImportIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={24} height={24} fill="none" viewBox="0 0 24 24" {...props}><path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M14 2.27V6.4c0 .56 0 .84.109 1.054a1 1 0 0 0 .437.437c.214.11.494.11 1.054.11h4.13M12.5 22h2.7c1.68 0 2.52 0 3.162-.327a3 3 0 0 0 1.311-1.311C20 19.72 20 18.88 20 17.2V8l-6-6H8.8c-1.68 0-2.52 0-3.162.327a3 3 0 0 0-1.311 1.311C4 4.28 4 5.12 4 6.8V12m3 4 3 3-3 3m3-3H4" /></svg>;
export default ImportIcon;