// Auto-generated by scripts/generate-icons.mjs — do not edit directly.
import AlertCmp from "./Alert";
import AlertTriangleIconCmp from "./AlertTriangleIcon";
import AreaIconCmp from "./AreaIcon";
import ArrowRightIconCmp from "./ArrowRightIcon";
import AvailableHeadingsIconCmp from "./AvailableHeadingsIcon";
import BackfillActivityIconCmp from "./BackfillActivityIcon";
import BackfillIconCmp from "./BackfillIcon";
import BarChartCmp from "./BarChart";
import BlastingIconCmp from "./BlastingIcon";
import BlocksIconCmp from "./BlocksIcon";
import BoreIconCmp from "./BoreIcon";
import BrokenStocksIconCmp from "./BrokenStocksIcon";
import CableBoltingIconCmp from "./CableBoltingIcon";
import CalendarCmp from "./Calendar";
import CalendarIconCmp from "./CalendarIcon";
import CalendarWeekIconCmp from "./CalendarWeekIcon";
import ChargingIconCmp from "./ChargingIcon";
import ChatBubbleIconCmp from "./ChatBubbleIcon";
import CheckIconCmp from "./CheckIcon";
import ChevronDownIconCmp from "./ChevronDownIcon";
import CleanIconCmp from "./CleanIcon";
import ClockCmp from "./Clock";
import CommentEmptyIconCmp from "./CommentEmptyIcon";
import CommentIconCmp from "./CommentIcon";
import CommentStatusIconCmp from "./CommentStatusIcon";
import ConeCmp from "./Cone";
import CrossIconCmp from "./CrossIcon";
import CrusherIconCmp from "./CrusherIcon";
import DashboardCmp from "./Dashboard";
import DataInputIconCmp from "./DataInputIcon";
import DeleteIconCmp from "./DeleteIcon";
import DozerWithTruckCmp from "./DozerWithTruck";
import DrillingIconCmp from "./DrillingIcon";
import EditIconCmp from "./EditIcon";
import EllipsisIconCmp from "./EllipsisIcon";
import EncircledCrossIconCmp from "./EncircledCrossIcon";
import EncircledExclamationIconCmp from "./EncircledExclamationIcon";
import EncircledTickIconCmp from "./EncircledTickIcon";
import FacePrepIconCmp from "./FacePrepIcon";
import FileIconCmp from "./FileIcon";
import FilledEncircledCrossIconCmp from "./FilledEncircledCrossIcon";
import FilledEncircledTickIconCmp from "./FilledEncircledTickIcon";
import FilterCmp from "./Filter";
import FlagIconCmp from "./FlagIcon";
import FolderIconCmp from "./FolderIcon";
import GarbageCanIconCmp from "./GarbageCanIcon";
import GeologyCmp from "./Geology";
import GeologyIconCmp from "./GeologyIcon";
import GoldBarsCmp from "./GoldBars";
import HaulTruckIconCmp from "./HaulTruckIcon";
import HaulTruckNavIconCmp from "./HaulTruckNavIcon";
import ImportIconCmp from "./ImportIcon";
import JumboCmp from "./Jumbo";
import LateralAdvanceIconCmp from "./LateralAdvanceIcon";
import LateralIconCmp from "./LateralIcon";
import LeftArrowIconCmp from "./LeftArrowIcon";
import LevelIconCmp from "./LevelIcon";
import LinkIconCmp from "./LinkIcon";
import LoaderIconCmp from "./LoaderIcon";
import LoadHaulCmp from "./LoadHaul";
import LoadStockpileCmp from "./LoadStockpile";
import LocationCmp from "./Location";
import LocationIconCmp from "./LocationIcon";
import LogoutCmp from "./Logout";
import LongHoleDrillIconCmp from "./LongHoleDrillIcon";
import LossTrackerIconCmp from "./LossTrackerIcon";
import MagnifyingGlassCmp from "./MagnifyingGlass";
import MaintenanceCmp from "./Maintenance";
import MeetingsCmp from "./Meetings";
import MillCmp from "./Mill";
import MinusIconCmp from "./MinusIcon";
import MuckingIconCmp from "./MuckingIcon";
import MvtActiveLinkCmp from "./MvtActiveLink";
import MvtActivityCmp from "./MvtActivity";
import MvtAgitatorTruckIconCmp from "./MvtAgitatorTruckIcon";
import MvtAncillaryIconCmp from "./MvtAncillaryIcon";
import MvtBogCycleCmp from "./MvtBogCycle";
import MvtChargeUpIconCmp from "./MvtChargeUpIcon";
import MvtConstrainedIconCmp from "./MvtConstrainedIcon";
import MvtCrossCmp from "./MvtCross";
import MvtDevCycleCmp from "./MvtDevCycle";
import MvtDevDrillIconCmp from "./MvtDevDrillIcon";
import MvtDiamondDrillIconCmp from "./MvtDiamondDrillIcon";
import MvtDrillCycleCmp from "./MvtDrillCycle";
import MvtEditCmp from "./MvtEdit";
import MvtExplosiveTruckIconCmp from "./MvtExplosiveTruckIcon";
import MVTIconCmp from "./MVTIcon";
import MvtInfoCircleCmp from "./MvtInfoCircle";
import MvtITIconCmp from "./MvtITIcon";
import MvtLinkCmp from "./MvtLink";
import MvtLoaderIconCmp from "./MvtLoaderIcon";
import MvtOnHoldIconCmp from "./MvtOnHoldIcon";
import MvtOpBoomDrillIconCmp from "./MvtOpBoomDrillIcon";
import MvtOpBulldozerIconCmp from "./MvtOpBulldozerIcon";
import MvtOpGraderIconCmp from "./MvtOpGraderIcon";
import MvtOpHaulTruckIconCmp from "./MvtOpHaulTruckIcon";
import MvtOpPaginiLoaderIconCmp from "./MvtOpPaginiLoaderIcon";
import MvtOpPlatformDrillIconCmp from "./MvtOpPlatformDrillIcon";
import MvtOpShovelIconCmp from "./MvtOpShovelIcon";
import MvtPaginiLoaderIconCmp from "./MvtPaginiLoaderIcon";
import MvtPasteFillIconCmp from "./MvtPasteFillIcon";
import MvtPriorityCmp from "./MvtPriority";
import MvtProdDrillIconCmp from "./MvtProdDrillIcon";
import MvtProductionCycleCmp from "./MvtProductionCycle";
import MvtRefugeChamberIconCmp from "./MvtRefugeChamberIcon";
import MvtServiceTruckIconCmp from "./MvtServiceTruckIcon";
import MvtShotcreterIconCmp from "./MvtShotcreterIcon";
import MvtStatusIconCmp from "./MvtStatusIcon";
import MvtSurfaceEquipmentIconCmp from "./MvtSurfaceEquipmentIcon";
import MvtSurfaceLoaderIconCmp from "./MvtSurfaceLoaderIcon";
import MvtTruckIconCmp from "./MvtTruckIcon";
import OpenPitCmp from "./OpenPit";
import OpportunitySectionIconCmp from "./OpportunitySectionIcon";
import OreTonnesIconCmp from "./OreTonnesIcon";
import PlusCircleCmp from "./PlusCircle";
import PlusCircleIconCmp from "./PlusCircleIcon";
import PlusIconCmp from "./PlusIcon";
import ProcessingPlantCmp from "./ProcessingPlant";
import ProductionsCmp from "./Productions";
import ProductionSectionIconCmp from "./ProductionSectionIcon";
import PulseCmp from "./Pulse";
import RaiseBoringIconCmp from "./RaiseBoringIcon";
import ReEntryIconCmp from "./ReEntryIcon";
import ReloadIconCmp from "./ReloadIcon";
import RemoveCircleCmp from "./RemoveCircle";
import RightArrowIconCmp from "./RightArrowIcon";
import RockCmp from "./Rock";
import RomStockpileIconCmp from "./RomStockpileIcon";
import SafetyCmp from "./Safety";
import SafetyHatCmp from "./SafetyHat";
import SafetySectionIconCmp from "./SafetySectionIcon";
import SaveCmp from "./Save";
import ScalingIconCmp from "./ScalingIcon";
import SearchCmp from "./Search";
import SendCmp from "./Send";
import SendIconCmp from "./SendIcon";
import ShiftIconCmp from "./ShiftIcon";
import ShotcreteIconCmp from "./ShotcreteIcon";
import SortIconCmp from "./SortIcon";
import StockpileCmp from "./Stockpile";
import StockpileIconCmp from "./StockpileIcon";
import StopeOreHauledIconCmp from "./StopeOreHauledIcon";
import StopeOreMuckedIconCmp from "./StopeOreMuckedIcon";
import StopeTrackerCmp from "./StopeTracker";
import SubmitIconCmp from "./SubmitIcon";
import TickIconCmp from "./TickIcon";
import TruckCmp from "./Truck";
import TumSectionIconCmp from "./TumSectionIcon";
import UndergroundCmp from "./Underground";
import VerticalIconCmp from "./VerticalIcon";
import WasteTonnesIconCmp from "./WasteTonnesIcon";
import WeeklyReportIconCmp from "./WeeklyReportIcon";

export const icons = {
  Alert: AlertCmp,
  AlertTriangleIcon: AlertTriangleIconCmp,
  AreaIcon: AreaIconCmp,
  ArrowRightIcon: ArrowRightIconCmp,
  AvailableHeadingsIcon: AvailableHeadingsIconCmp,
  BackfillActivityIcon: BackfillActivityIconCmp,
  BackfillIcon: BackfillIconCmp,
  BarChart: BarChartCmp,
  BlastingIcon: BlastingIconCmp,
  BlocksIcon: BlocksIconCmp,
  BoreIcon: BoreIconCmp,
  BrokenStocksIcon: BrokenStocksIconCmp,
  CableBoltingIcon: CableBoltingIconCmp,
  Calendar: CalendarCmp,
  CalendarIcon: CalendarIconCmp,
  CalendarWeekIcon: CalendarWeekIconCmp,
  ChargingIcon: ChargingIconCmp,
  ChatBubbleIcon: ChatBubbleIconCmp,
  CheckIcon: CheckIconCmp,
  ChevronDownIcon: ChevronDownIconCmp,
  CleanIcon: CleanIconCmp,
  Clock: ClockCmp,
  CommentEmptyIcon: CommentEmptyIconCmp,
  CommentIcon: CommentIconCmp,
  CommentStatusIcon: CommentStatusIconCmp,
  Cone: ConeCmp,
  CrossIcon: CrossIconCmp,
  CrusherIcon: CrusherIconCmp,
  Dashboard: DashboardCmp,
  DataInputIcon: DataInputIconCmp,
  DeleteIcon: DeleteIconCmp,
  DozerWithTruck: DozerWithTruckCmp,
  DrillingIcon: DrillingIconCmp,
  EditIcon: EditIconCmp,
  EllipsisIcon: EllipsisIconCmp,
  EncircledCrossIcon: EncircledCrossIconCmp,
  EncircledExclamationIcon: EncircledExclamationIconCmp,
  EncircledTickIcon: EncircledTickIconCmp,
  FacePrepIcon: FacePrepIconCmp,
  FileIcon: FileIconCmp,
  FilledEncircledCrossIcon: FilledEncircledCrossIconCmp,
  FilledEncircledTickIcon: FilledEncircledTickIconCmp,
  Filter: FilterCmp,
  FlagIcon: FlagIconCmp,
  FolderIcon: FolderIconCmp,
  GarbageCanIcon: GarbageCanIconCmp,
  Geology: GeologyCmp,
  GeologyIcon: GeologyIconCmp,
  GoldBars: GoldBarsCmp,
  HaulTruckIcon: HaulTruckIconCmp,
  HaulTruckNavIcon: HaulTruckNavIconCmp,
  ImportIcon: ImportIconCmp,
  Jumbo: JumboCmp,
  LateralAdvanceIcon: LateralAdvanceIconCmp,
  LateralIcon: LateralIconCmp,
  LeftArrowIcon: LeftArrowIconCmp,
  LevelIcon: LevelIconCmp,
  LinkIcon: LinkIconCmp,
  LoaderIcon: LoaderIconCmp,
  LoadHaul: LoadHaulCmp,
  LoadStockpile: LoadStockpileCmp,
  Location: LocationCmp,
  LocationIcon: LocationIconCmp,
  Logout: LogoutCmp,
  LongHoleDrillIcon: LongHoleDrillIconCmp,
  LossTrackerIcon: LossTrackerIconCmp,
  MagnifyingGlass: MagnifyingGlassCmp,
  Maintenance: MaintenanceCmp,
  Meetings: MeetingsCmp,
  Mill: MillCmp,
  MinusIcon: MinusIconCmp,
  MuckingIcon: MuckingIconCmp,
  MvtActiveLink: MvtActiveLinkCmp,
  MvtActivity: MvtActivityCmp,
  MvtAgitatorTruckIcon: MvtAgitatorTruckIconCmp,
  MvtAncillaryIcon: MvtAncillaryIconCmp,
  MvtBogCycle: MvtBogCycleCmp,
  MvtChargeUpIcon: MvtChargeUpIconCmp,
  MvtConstrainedIcon: MvtConstrainedIconCmp,
  MvtCross: MvtCrossCmp,
  MvtDevCycle: MvtDevCycleCmp,
  MvtDevDrillIcon: MvtDevDrillIconCmp,
  MvtDiamondDrillIcon: MvtDiamondDrillIconCmp,
  MvtDrillCycle: MvtDrillCycleCmp,
  MvtEdit: MvtEditCmp,
  MvtExplosiveTruckIcon: MvtExplosiveTruckIconCmp,
  MVTIcon: MVTIconCmp,
  MvtInfoCircle: MvtInfoCircleCmp,
  MvtITIcon: MvtITIconCmp,
  MvtLink: MvtLinkCmp,
  MvtLoaderIcon: MvtLoaderIconCmp,
  MvtOnHoldIcon: MvtOnHoldIconCmp,
  MvtOpBoomDrillIcon: MvtOpBoomDrillIconCmp,
  MvtOpBulldozerIcon: MvtOpBulldozerIconCmp,
  MvtOpGraderIcon: MvtOpGraderIconCmp,
  MvtOpHaulTruckIcon: MvtOpHaulTruckIconCmp,
  MvtOpPaginiLoaderIcon: MvtOpPaginiLoaderIconCmp,
  MvtOpPlatformDrillIcon: MvtOpPlatformDrillIconCmp,
  MvtOpShovelIcon: MvtOpShovelIconCmp,
  MvtPaginiLoaderIcon: MvtPaginiLoaderIconCmp,
  MvtPasteFillIcon: MvtPasteFillIconCmp,
  MvtPriority: MvtPriorityCmp,
  MvtProdDrillIcon: MvtProdDrillIconCmp,
  MvtProductionCycle: MvtProductionCycleCmp,
  MvtRefugeChamberIcon: MvtRefugeChamberIconCmp,
  MvtServiceTruckIcon: MvtServiceTruckIconCmp,
  MvtShotcreterIcon: MvtShotcreterIconCmp,
  MvtStatusIcon: MvtStatusIconCmp,
  MvtSurfaceEquipmentIcon: MvtSurfaceEquipmentIconCmp,
  MvtSurfaceLoaderIcon: MvtSurfaceLoaderIconCmp,
  MvtTruckIcon: MvtTruckIconCmp,
  OpenPit: OpenPitCmp,
  OpportunitySectionIcon: OpportunitySectionIconCmp,
  OreTonnesIcon: OreTonnesIconCmp,
  PlusCircle: PlusCircleCmp,
  PlusCircleIcon: PlusCircleIconCmp,
  PlusIcon: PlusIconCmp,
  ProcessingPlant: ProcessingPlantCmp,
  Productions: ProductionsCmp,
  ProductionSectionIcon: ProductionSectionIconCmp,
  Pulse: PulseCmp,
  RaiseBoringIcon: RaiseBoringIconCmp,
  ReEntryIcon: ReEntryIconCmp,
  ReloadIcon: ReloadIconCmp,
  RemoveCircle: RemoveCircleCmp,
  RightArrowIcon: RightArrowIconCmp,
  Rock: RockCmp,
  RomStockpileIcon: RomStockpileIconCmp,
  Safety: SafetyCmp,
  SafetyHat: SafetyHatCmp,
  SafetySectionIcon: SafetySectionIconCmp,
  Save: SaveCmp,
  ScalingIcon: ScalingIconCmp,
  Search: SearchCmp,
  Send: SendCmp,
  SendIcon: SendIconCmp,
  ShiftIcon: ShiftIconCmp,
  ShotcreteIcon: ShotcreteIconCmp,
  SortIcon: SortIconCmp,
  Stockpile: StockpileCmp,
  StockpileIcon: StockpileIconCmp,
  StopeOreHauledIcon: StopeOreHauledIconCmp,
  StopeOreMuckedIcon: StopeOreMuckedIconCmp,
  StopeTracker: StopeTrackerCmp,
  SubmitIcon: SubmitIconCmp,
  TickIcon: TickIconCmp,
  Truck: TruckCmp,
  TumSectionIcon: TumSectionIconCmp,
  Underground: UndergroundCmp,
  VerticalIcon: VerticalIconCmp,
  WasteTonnesIcon: WasteTonnesIconCmp,
  WeeklyReportIcon: WeeklyReportIconCmp,
} as const;

export type IconName = keyof typeof icons;
