// Auto-generated by scripts/generate-icons.mjs from icons/LateralIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const LateralIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={24} height={24} fill="none" stroke="currentColor" viewBox="0 0 24 24" {...props}><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.75} d="M21 12H3m18 0-4 4m4-4-4-4M3 12l4 4m-4-4 4-4" /></svg>;
export default LateralIcon;