// Auto-generated by scripts/generate-icons.mjs from icons/LeftArrowIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const LeftArrowIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={12} height={12} fill="none" stroke="currentcolor" viewBox="0 0 12 12" {...props}><path strokeLinecap="round" strokeLinejoin="round" d="M10 6H2m0 0 3 3M2 6l3-3" /></svg>;
export default LeftArrowIcon;