// Auto-generated by scripts/generate-icons.mjs from icons/LevelIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const LevelIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={12} height={17} fill="none" viewBox="0 0 12 17" {...props}><g clipPath="url(#a)"><path stroke="currentcolor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={0.75} d="m1 9.75 4.821 2.41c.066.033.099.05.133.056a.3.3 0 0 0 .092 0c.034-.006.067-.023.133-.055L11 9.75M1 7.25l4.821-2.41c.066-.033.099-.05.133-.056a.3.3 0 0 1 .092 0c.034.006.067.023.133.055L11 7.25 6.179 9.66c-.066.033-.099.05-.133.056a.3.3 0 0 1-.092 0c-.034-.006-.067-.023-.133-.055z" /></g><defs><clipPath id="a"><path fill="#fff" d="M0 2.5h12v12H0z" /></clipPath></defs></svg>;
export default LevelIcon;