// Auto-generated by scripts/generate-icons.mjs from icons/LoadStockpile.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const LoadStockpile = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={17} height={16} fill="none" viewBox="0 0 17 16" {...props}><path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.25} d="M7.218 7.179H7.21m2.673 0h-.006M8.55 5.245h-.007m6.062 4.749-2.4-3.866c-1.207-1.944-1.81-2.916-2.59-3.245a2.75 2.75 0 0 0-2.137 0c-.78.33-1.383 1.301-2.59 3.245l-2.4 3.866c-.226.365-.34.547-.42.742a2.5 2.5 0 0 0-.153.536c-.035.207-.035.42-.035.845v.185c0 .361 0 .542.073.68.063.12.165.22.29.281.143.07.33.07.704.07h11.2c.373 0 .56 0 .702-.07a.66.66 0 0 0 .292-.282c.072-.137.072-.318.072-.679v-.185c0-.425 0-.638-.035-.845a2.5 2.5 0 0 0-.154-.536c-.08-.195-.193-.377-.42-.742" /></svg>;
export default LoadStockpile;