// Auto-generated by scripts/generate-icons.mjs from icons/LocationIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const LocationIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={17} height={16} fill="none" stroke="currentcolor" viewBox="0 0 17 16" {...props}><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.25} d="M8.801 8.667a2 2 0 1 0 0-4 2 2 0 0 0 0 4" /><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.25} d="M8.801 14.667c2.667-2.667 5.334-5.055 5.334-8a5.333 5.333 0 1 0-10.667 0c0 2.945 2.667 5.333 5.333 8" /></svg>;
export default LocationIcon;