// Auto-generated by scripts/generate-icons.mjs from icons/LongHoleDrillIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const LongHoleDrillIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={60} height={26} fill="none" viewBox="0 0 60 26" {...props}><mask id="a" width={43} height={26} x={0} y={0} maskUnits="userSpaceOnUse" style={{
    maskType: "alpha"
  }}><path stroke="#000" strokeLinecap="round" strokeWidth={3} d="M40.375 1 2 13.832m32.823-2.115-23.025 7.699m25.147.451L21.595 25" /></mask><g mask="url(#a)"><path fill="#fff" d="M-8.714-.548h58.612v29.714H-8.714z" /></g></svg>;
export default LongHoleDrillIcon;