// Auto-generated by scripts/generate-icons.mjs from icons/Meetings.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const Meetings = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={24} height={24} fill="none" viewBox="0 0 24 24" {...props}><path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.75} d="M18 15.837c1.456.731 2.704 1.905 3.615 3.373.18.29.27.436.302.637.063.409-.216.912-.597 1.073-.188.08-.398.08-.82.08M16 11.532a4.5 4.5 0 0 0 0-8.064M14 7.5a4.5 4.5 0 1 1-9 0 4.5 4.5 0 0 1 9 0M2.56 18.938C4.152 16.545 6.67 15 9.5 15s5.346 1.545 6.94 3.938c.35.525.524.787.504 1.122-.015.26-.186.58-.395.738-.267.202-.635.202-1.371.202H3.822c-.736 0-1.104 0-1.372-.202a1.1 1.1 0 0 1-.395-.738c-.02-.335.155-.597.504-1.122" /></svg>;
export default Meetings;