// Auto-generated by scripts/generate-icons.mjs from icons/MuckingIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const MuckingIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={24} height={24} fill="none" stroke="currentcolor" viewBox="0 0 24 24" {...props}><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.75} d="m12.795 13.17 3.546-2.048 2.73 4.731a4.1 4.1 0 0 1-1.5 5.597 4.09 4.09 0 0 1-5.592-1.5l-2.73-4.73zm0 0-5.46-9.463m5.46 9.463 1.365 2.366M4.38 5.415l2.956-1.708m0 0L10.29 2" /></svg>;
export default MuckingIcon;