// Auto-generated by scripts/generate-icons.mjs from icons/mvt/ActiveLink.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const MvtActiveLink = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={13} height={13} fill="none" viewBox="0 0 13 13" {...props}><path stroke="#B08824" strokeLinecap="round" strokeLinejoin="round" d="M12.5 4.5v-4m0 0h-4m4 0L7.167 5.833m-2-4H3.7c-1.12 0-1.68 0-2.108.218a2 2 0 0 0-.874.874C.5 3.353.5 3.913.5 5.033V9.3c0 1.12 0 1.68.218 2.108a2 2 0 0 0 .874.874c.428.218.988.218 2.108.218h4.267c1.12 0 1.68 0 2.108-.218a2 2 0 0 0 .874-.874c.218-.428.218-.988.218-2.108V7.833" /></svg>;
export default MvtActiveLink;