// Auto-generated by scripts/generate-icons.mjs from icons/mvt/Activity.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const MvtActivity = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={12} height={12} fill="none" viewBox="0 0 12 12" {...props}><g clipPath="url(#a)"><path stroke="#D6D6D6" strokeLinecap="round" strokeLinejoin="round" strokeWidth={0.75} d="M11 6H9l-1.5 4.5-3-9L3 6H1" /></g><defs><clipPath id="a"><path fill="#fff" d="M0 0h12v12H0z" /></clipPath></defs></svg>;
export default MvtActivity;