// Auto-generated by scripts/generate-icons.mjs from icons/mvt/Cross.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const MvtCross = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width="width" height="height" fill="none" viewBox="0 0 8 8" {...props}><path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" d="M7.167.5.5 7.167M.5.5l6.667 6.667" /></svg>;
export default MvtCross;