// Auto-generated by scripts/generate-icons.mjs from icons/mvt/Edit.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const MvtEdit = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width="width" height="height" fill="none" viewBox="0 0 16 16" {...props}><path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" d="M12 6.666 9.332 4M1.666 14.333l2.256-.25c.276-.031.414-.047.543-.088a1.3 1.3 0 0 0 .323-.156c.113-.074.211-.173.407-.369L14 4.666A1.886 1.886 0 0 0 11.333 2l-8.804 8.804c-.197.196-.295.294-.37.407q-.099.151-.155.323c-.041.13-.057.267-.087.543z" /></svg>;
export default MvtEdit;