// Auto-generated by scripts/generate-icons.mjs from icons/MVTIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const MVTIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={24} height={24} fill="none" viewBox="0 0 24 24" {...props}><path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.75} d="M10.005 10.768h-.01m4.01 0h-.01m-1.99-2.9h-.01m9.092 7.123-3.6-5.8c-1.81-2.915-2.715-4.373-3.885-4.867a4.13 4.13 0 0 0-3.204 0c-1.17.494-2.075 1.952-3.885 4.868l-3.6 5.799c-.34.547-.51.82-.63 1.113q-.16.39-.23.804C2 17.218 2 17.538 2 18.175v.278c0 .541 0 .812.109 1.02.096.181.249.329.437.422C2.76 20 3.04 20 3.6 20h16.8c.56 0 .84 0 1.054-.105a1 1 0 0 0 .437-.423c.109-.207.109-.478.109-1.019v-.277c0-.639 0-.958-.052-1.268a3.8 3.8 0 0 0-.231-.804c-.12-.292-.29-.566-.63-1.113" /></svg>;
export default MVTIcon;