// Auto-generated by scripts/generate-icons.mjs from icons/mvt/PasteFillIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const MvtPasteFillIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={40} height={40} fill="none" viewBox="0 0 40 40" {...props}><path stroke="#fff" strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M35 18.333V27c0 2.8 0 4.2-.545 5.27a5 5 0 0 1-2.185 2.185C31.2 35 29.8 35 27 35H13c-2.8 0-4.2 0-5.27-.545a5 5 0 0 1-2.185-2.185C5 31.2 5 29.8 5 27v-8.667M9.984 30h-.017m6.667 0h.033m-3.35-4.834h-.016M23.317 30h.05M20 25.166h-.016M30.033 30h-.017M26.7 25.166h-.017m-5.546-13.034-.032.008m-4.47-3.807.016-.004M21.636 18l-.029-.016M5 5h7.5v6.667H5" /></svg>;
export default MvtPasteFillIcon;