// Auto-generated by scripts/generate-icons.mjs from icons/mvt/Priority.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const MvtPriority = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={12} height={12} fill="none" viewBox="0 0 12 12" {...props}><path stroke="#D6D6D6" strokeLinecap="round" strokeLinejoin="round" strokeWidth={0.75} d="M2 7.5S2.5 7 4 7s2.5 1 4 1 2-.5 2-.5v-6S9.5 2 8 2 5.5 1 4 1s-2 .5-2 .5V11" /></svg>;
export default MvtPriority;