// Auto-generated by scripts/generate-icons.mjs from icons/mvt/StatusIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const MvtStatusIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={12} height={17} fill="currentColor" viewBox="0 0 12 17" {...props}><path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={0.75} d="M6 3.625v1.25M6 11.5v2m-3.125-5h-1.75m9.5 0h-.75m-.646 3.229-.354-.354m.457-6.167-.707.707m-6.164 6.124 1.414-1.414m-1.31-5.52 1.06 1.06" /></svg>;
export default MvtStatusIcon;