// Auto-generated by scripts/generate-icons.mjs from icons/OpportunitySectionIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const OpportunitySectionIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={20} height={20} fill="none" viewBox="0 0 20 20" {...props}><path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M7.917 18.333h4.166m-3.75-10h3.334m-1.667 0v5m2.5-.561a5.834 5.834 0 1 0-5 0v.561c0 .777 0 1.165.127 1.471.17.409.494.733.902.902.306.127.695.127 1.471.127s1.165 0 1.471-.127c.409-.169.733-.493.902-.902.127-.306.127-.694.127-1.47z" /></svg>;
export default OpportunitySectionIcon;