// Auto-generated by scripts/generate-icons.mjs from icons/PlusCircle.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const PlusCircle = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={16} height={16} fill="none" viewBox="0 0 16 16" {...props}><g clipPath="url(#a)"><path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" d="M8 5.333v5.334M5.333 8h5.333m4 0A6.667 6.667 0 1 1 1.333 8a6.667 6.667 0 0 1 13.333 0" /></g><defs><clipPath id="a"><path fill="#fff" d="M0 0h16v16H0z" /></clipPath></defs></svg>;
export default PlusCircle;