// Auto-generated by scripts/generate-icons.mjs from icons/ProcessingPlant.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const ProcessingPlant = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={24} height={24} fill="none" viewBox="0 0 24 24" {...props}><path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15.024 22H4.817c2.193-4.26 2.48-10.128 2.35-12.53h5.508c-.054.99-.037 2.566.155 4.376M15.024 22c-1.29-2.506-1.92-5.568-2.194-8.154M15.024 22h4.158c-1.771-3.441-2.003-8.181-1.897-10.12h-4.45a20 20 0 0 1-.005 1.966M16.8 2a2.29 2.29 0 0 1-2.289 2.289h-2.911a2.29 2.29 0 0 0-2.29 2.289M19.38 6.06a.964.964 0 0 1-.965.964h-1.227a.964.964 0 0 0-.964.965" /></svg>;
export default ProcessingPlant;