// Auto-generated by scripts/generate-icons.mjs from icons/Productions.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const Productions = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={18} height={12} fill="none" viewBox="0 0 18 12" {...props}><path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.25} d="M11.36 7.112h4.721l1.21 4.106H10.15zM6.597.625h4.722l1.21 4.106H5.388zM1.836 7.112h4.721l1.21 4.106H.626z" /></svg>;
export default Productions;