// Auto-generated by scripts/generate-icons.mjs from icons/Pulse.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const Pulse = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={17} height={16} fill="none" viewBox="0 0 17 16" {...props}><path stroke="currentcolor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.25} d="M15.214 8h-2.666l-2 6-4-12-2 6H1.88" /></svg>;
export default Pulse;