// Auto-generated by scripts/generate-icons.mjs from icons/RaiseBoringIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const RaiseBoringIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={24} height={24} fill="none" stroke="currentcolor" viewBox="0 0 24 24" {...props}><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.75} d="M12 22V3M8 2v3.002M8 10V5.002M16 2v3.002M16 10V5.002m-8 0h8M7.004 10h2M15 10h2M8.004 22H16" /></svg>;
export default RaiseBoringIcon;