// Auto-generated by scripts/generate-icons.mjs from icons/ReEntryIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const ReEntryIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={40} height={40} fill="none" viewBox="0 0 40 40" {...props}><path stroke="currentcolor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 5h5.625M35 5h-5.625m0 0h-18.75m18.75 0 3.75 19.999M10.625 5 5 35m7.5 0V19.167a7.5 7.5 0 1 1 15 0v2.5m-9.167 9.167L23.691 35m-5.358-4.166 5.358-4.167m-5.358 4.167H35" /></svg>;
export default ReEntryIcon;