// Auto-generated by scripts/generate-icons.mjs from icons/ReloadIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const ReloadIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={16} height={16} fill="none" viewBox="0 0 16 16" {...props}><path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" d="M1.333 6.667S2.67 4.845 3.756 3.759a6 6 0 1 1-1.521 5.908m3.098-3h-4v-4" /></svg>;
export default ReloadIcon;