// Auto-generated by scripts/generate-icons.mjs from icons/RemoveCircle.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const RemoveCircle = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={16} height={20} fill="none" viewBox="0 0 16 20" {...props}><g clipPath="url(#clip0_394_1072)"><path stroke="currentcolor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M5.333 10h5.334m4 0a6.667 6.667 0 1 1-13.334 0 6.667 6.667 0 0 1 13.334 0" /></g></svg>;
export default RemoveCircle;