// Auto-generated by scripts/generate-icons.mjs from icons/RightArrowIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const RightArrowIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={12} height={12} fill="none" stroke="currentcolor" viewBox="0 0 12 12" {...props}><path strokeLinecap="round" strokeLinejoin="round" d="M2 6h8m0 0L7 3m3 3L7 9" /></svg>;
export default RightArrowIcon;