// Auto-generated by scripts/generate-icons.mjs from icons/RomStockpileIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const RomStockpileIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={16} height={16} fill="none" viewBox="0 0 16 16" {...props}><path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.25} d="M1.333 4c0-.736.61-1.333 1.364-1.333.753 0 1.364.597 1.364 1.333v8c0 .736-.61 1.333-1.364 1.333-.753 0-1.364-.597-1.364-1.333zM11.94 4c0-.736.61-1.333 1.363-1.333s1.364.597 1.364 1.333v8c0 .736-.61 1.333-1.364 1.333-.753 0-1.364-.597-1.364-1.333zM6.636 4c0-.736.61-1.333 1.364-1.333.753 0 1.364.597 1.364 1.333v8c0 .736-.61 1.333-1.364 1.333-.753 0-1.364-.597-1.364-1.333z" /></svg>;
export default RomStockpileIcon;