// Auto-generated by scripts/generate-icons.mjs from icons/Safety.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const Safety = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={24} height={24} fill="none" viewBox="0 0 24 24" {...props}><path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M22 18.836H2m8.5-3H4v-1.672c0-2.328.995-4.425 2.582-5.886A8 8 0 0 1 10.058 6.4m.442 9.435h3m-3 0-.442-9.435m3.442 9.435H20v-1.672a7.98 7.98 0 0 0-2.614-5.916 8 8 0 0 0-3.444-1.847m-.442 9.435.442-9.435m0 0a1.18 1.18 0 0 0-1.18-1.237h-1.523c-.675 0-1.213.563-1.181 1.237v0" /></svg>;
export default Safety;