// Auto-generated by scripts/generate-icons.mjs from icons/SafetySectionIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const SafetySectionIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={19} height={17} fill="none" viewBox="0 0 19 17" {...props}><path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9.303 6.17v3.333m0 3.334h.008M8.15 1.913l-6.854 11.84c-.38.656-.57.984-.542 1.254a.83.83 0 0 0 .338.587c.22.16.599.16 1.358.16h13.708c.759 0 1.138 0 1.357-.16a.83.83 0 0 0 .339-.587c.028-.27-.162-.598-.542-1.255L10.457 1.913c-.38-.654-.568-.981-.816-1.091a.83.83 0 0 0-.677 0c-.247.11-.436.437-.815 1.091" /></svg>;
export default SafetySectionIcon;