// Auto-generated by scripts/generate-icons.mjs from icons/ScalingIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const ScalingIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={40} height={40} fill="none" viewBox="0 0 40 40" {...props}><path stroke="currentcolor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M32.619 13.333H35m-8.333-5.952V5m4.864 3.47 1.683-1.684M14.631 31.882a3.118 3.118 0 1 1-6.236 0m6.236 0a3.12 3.12 0 0 0-3.118-3.118m3.118 3.118h6.235m-12.47 0a3.12 3.12 0 0 1 3.117-3.118m-3.118 3.118H5v-8.101h6.524m-.011 4.983.01-4.983m18.414 8.101a3.118 3.118 0 1 1-6.236 0m6.236 0a3.118 3.118 0 1 0-6.236 0m6.236 0h3.396l.217-4.968c.047-1.09-.824-2-1.915-2m-7.934 6.968h-2.835m-9.342-8.101-.011-4.535h6.247l3.106 5.668m0 0h10.769m-10.769 0v6.968m10.77-6.968L25 16.667l2.218-3.327" /></svg>;
export default ScalingIcon;