// Auto-generated by scripts/generate-icons.mjs from icons/Search.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const Search = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={12} height={12} fill="none" viewBox="0 0 12 12" {...props}><path stroke="#D6D6D6" strokeLinecap="round" strokeLinejoin="round" strokeWidth={0.75} d="M10.5 10.5 8.325 8.325M9.5 5.5a4 4 0 1 1-8 0 4 4 0 0 1 8 0" /></svg>;
export default Search;