// Auto-generated by scripts/generate-icons.mjs from icons/Send.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const Send = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={14} height={12} fill="none" viewBox="0 0 14 12" {...props}><path stroke="currentcolor" strokeLinecap="round" strokeLinejoin="round" d="M6 6H2.33m-.05.194-1.56 4.65c-.12.365-.18.548-.14.661.04.097.12.171.22.2.12.032.29-.047.65-.205l11.14-5.014c.34-.154.51-.231.56-.338a.31.31 0 0 0 0-.296c-.05-.107-.22-.184-.56-.338L1.44.499C1.09.341.92.262.8.294a.34.34 0 0 0-.22.2c-.05.112.02.294.14.659l1.56 4.704c.02.063.03.094.03.126q.015.042 0 .086c0 .032-.01.063-.03.125" /></svg>;
export default Send;