// Auto-generated by scripts/generate-icons.mjs from icons/SendIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const SendIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={13} height={12} fill="none" viewBox="0 0 13 12" {...props}><path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.25} d="M5.6 5.8H1.934m-.057.194-1.556 4.65c-.123.365-.184.548-.14.66.038.098.12.172.22.2.117.033.293-.046.644-.204l11.141-5.014c.343-.154.514-.231.567-.338a.33.33 0 0 0 0-.296c-.053-.107-.224-.184-.567-.338L1.041.298C.691.141.516.062.4.094a.33.33 0 0 0-.221.2C.135.406.195.588.316.953l1.562 4.704c.02.063.03.094.035.126a.3.3 0 0 1 0 .085c-.004.032-.015.064-.036.126" /></svg>;
export default SendIcon;