// Auto-generated by scripts/generate-icons.mjs from icons/ShotcreteIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const ShotcreteIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={40} height={40} fill="none" viewBox="0 0 40 40" {...props}><path stroke="currentcolor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11.992 9.601h-1.16a5.833 5.833 0 0 0 0 11.666h20.836a3.333 3.333 0 0 1 0 6.666H8.534a3.533 3.533 0 1 0 0 7.067h26.467M11.992 13.768V5.435m19.8 6.46v.01m0-4.608v.012m-3.333 2.287v.011M35 9.597v.011M35 5v.011m0 9.18v.012M16.157 7.1l7.603.836v3.334l-7.603.83z" /></svg>;
export default ShotcreteIcon;