// Auto-generated by scripts/generate-icons.mjs from icons/SortIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const SortIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={6} height={9} fill="none" viewBox="0 0 6 9" {...props}><path stroke="currentColor" strokeLinecap="round" d="M.5 3 3 .5 5.5 3M.5 6 3 8.5 5.5 6" /></svg>;
export default SortIcon;