// Auto-generated by scripts/generate-icons.mjs from icons/StockpileIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const StockpileIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={15} height={12} fill="none" viewBox="0 0 15 12" {...props}><path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.25} d="M5.962 5.137h-.007m2.673 0h-.006M7.295 3.203h-.007m6.062 4.75-2.4-3.867C9.743 2.142 9.14 1.171 8.36.841a2.75 2.75 0 0 0-2.136 0c-.78.33-1.384 1.301-2.59 3.245l-2.4 3.866c-.227.365-.34.547-.42.742a2.5 2.5 0 0 0-.154.536c-.035.207-.035.42-.035.845v.185c0 .361 0 .542.073.68.064.121.166.22.291.281.143.07.33.07.703.07h11.2c.373 0 .56 0 .702-.07a.66.66 0 0 0 .292-.281c.072-.138.072-.319.072-.68v-.185c0-.425 0-.638-.035-.845a2.5 2.5 0 0 0-.153-.536c-.08-.195-.194-.377-.42-.742" /></svg>;
export default StockpileIcon;