// Auto-generated by scripts/generate-icons.mjs from icons/StopeTracker.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const StopeTracker = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={22} height={16} fill="none" viewBox="0 0 22 16" {...props}><path stroke="currentcolor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.75} d="M15 1.066h5m-8.27 8.212h5M14 4.066h7m-4.27 0v6.712M5.735 13.066a1.867 1.867 0 1 0-3.735 0m3.735 0a1.867 1.867 0 1 1-3.735 0m3.735 0h3.398m-7.133 0H1V7.528l5.73-.75v-1.5h2.5l2.5 2v4.069m-2.597 1.72a1.868 1.868 0 0 1 2.597-1.72m-2.597 1.72a1.867 1.867 0 1 0 2.597-1.72" /></svg>;
export default StopeTracker;