// Auto-generated by scripts/generate-icons.mjs from icons/SubmitIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const SubmitIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={12} height={12} fill="none" viewBox="0 0 12 12" {...props}><path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={0.75} d="M5.25 6H2.5m-.042.146L1.291 9.633c-.092.274-.138.411-.105.495a.25.25 0 0 0 .166.15c.087.025.219-.035.482-.153l8.356-3.76c.257-.116.386-.174.426-.254a.25.25 0 0 0 0-.222c-.04-.08-.169-.138-.426-.254L1.831 1.874c-.262-.118-.394-.177-.48-.153a.25.25 0 0 0-.166.15c-.033.084.012.22.103.494l1.17 3.528c.016.047.024.07.027.094a.3.3 0 0 1 0 .064.5.5 0 0 1-.027.095" /></svg>;
export default SubmitIcon;