// Auto-generated by scripts/generate-icons.mjs from icons/TickIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const TickIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={13} height={12} fill="none" viewBox="0 0 13 12" {...props}><path stroke="currentcolor" strokeLinecap="round" strokeLinejoin="round" d="m10.801 3-5.5 5.5-2.5-2.5" /></svg>;
export default TickIcon;