// Auto-generated by scripts/generate-icons.mjs from icons/Truck.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const Truck = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={13} height={13} fill="none" viewBox="0 0 13 13" {...props}><g clipPath="url(#a)"><path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" d="M7.543 3.163v5.28h-.581m.58-5.28-1.141.52H3.772L1.667 5.164l.942 3.279h.315m4.619-5.28h1.896m-6.515 5.28a.947.947 0 1 0 1.67.895.947.947 0 0 0-1.67-.895m4.038 0a.947.947 0 1 0-1.67.894.947.947 0 0 0 1.67-.894m2.514 0a.947.947 0 1 0 1.67 0m-1.67 0a.947.947 0 0 1 1.67 0m-1.67 0h-.51V4.581h1.35l1.35 1.681v2.181h-.52" /></g><defs><clipPath id="a"><path fill="#fff" d="M.667.5h12v12h-12z" /></clipPath></defs></svg>;
export default Truck;