// Auto-generated by scripts/generate-icons.mjs from icons/Underground.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const Underground = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={24} height={24} fill="none" viewBox="0 0 24 24" {...props}><path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15.051 14.837V9.192a3.05 3.05 0 0 0-6.101 0v5.645m6.101 0H8.95m6.101 0 1.579 3.269m-7.68-3.27-1.579 3.27m0 0-1.579 3.269H18.21l-1.58-3.27m-9.258 0h9.259M2 2.626h3.75m16.25 0h-3.75m0 0H5.75m12.5 0L22 21.375M5.75 2.625 2 21.375" /></svg>;
export default Underground;