// Auto-generated by scripts/generate-icons.mjs from icons/VerticalIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const VerticalIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={24} height={24} fill="none" stroke="currentcolor" viewBox="0 0 24 24" {...props}><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.75} d="M12 21V3m0 18-4-4m4 4 4-4M12 3 8 7m4-4 4 4" /></svg>;
export default VerticalIcon;