// Auto-generated by scripts/generate-icons.mjs from icons/WasteTonnesIcon.svg.
// Do not edit directly — edit the source SVG and run `npm run generate`.
import * as React from "react";
import type { SVGProps } from "react";
const WasteTonnesIcon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" width={21} height={25} fill="none" viewBox="0 0 21 25" {...props}><path fill="#fff" stroke="#fff" d="M18.926 8.198a.45.45 0 0 1 .442.336q.015.05.017.1l-.005.101-2.557 15.387a.452.452 0 0 1-.445.378H4.622a.45.45 0 0 1-.425-.3l-.02-.078L1.619 8.735h.001a.47.47 0 0 1 .103-.375.46.46 0 0 1 .246-.151l.096-.01zM6.682.5h7.636a.45.45 0 0 1 .32.134.47.47 0 0 1 .135.328v3.387h5.273a.45.45 0 0 1 .32.134.466.466 0 0 1 0 .657.45.45 0 0 1-.32.133H.954a.45.45 0 0 1-.32-.133.466.466 0 0 1 0-.657.45.45 0 0 1 .32-.134h5.274V.962c0-.124.049-.242.134-.328A.45.45 0 0 1 6.682.5Zm.455 3.849h6.726V1.425H7.137z" /></svg>;
export default WasteTonnesIcon;