// Regenerates src/icons/**/*.tsx from the raw SVG source of truth in icons/.
// Run via `npm run generate` (also runs automatically before `npm run build`).
// Icons pushed here by the Figma export pipeline are picked up the same way.
import { transform } from "@svgr/core";
import { mkdirSync, writeFileSync, rmSync } from "node:fs";
import { join, relative, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { svgoConfig, readIcons } from "./lib/icons.mjs";

const rootDir = dirname(fileURLToPath(import.meta.url)) + "/..";
const sourceDir = join(rootDir, "icons");
const outDir = join(rootDir, "src", "icons");

async function main() {
  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(outDir, { recursive: true });

  const icons = readIcons(sourceDir);

  for (const { filePath, componentName, svgCode } of icons) {
    const tsx = await transform(
      svgCode,
      {
        typescript: true,
        icon: false,
        plugins: ["@svgr/plugin-svgo", "@svgr/plugin-jsx"],
        svgoConfig,
      },
      { componentName }
    );

    const header = `// Auto-generated by scripts/generate-icons.mjs from icons/${relative(sourceDir, filePath).replace(/\\/g, "/")}.\n// Do not edit directly — edit the source SVG and run \`npm run generate\`.\n`;
    writeFileSync(join(outDir, `${componentName}.tsx`), header + tsx);
  }

  const entries = icons.map((i) => i.componentName);

  // Icons are intentionally NOT re-exported individually — SezzyIcon (by
  // name) is the only public way to render one, so every consumer goes
  // through one consistent API. This barrel stays internal to src/icons/.
  const barrel = [
    "// Auto-generated by scripts/generate-icons.mjs — do not edit directly.",
    ...entries.map((name) => `import ${name}Cmp from "./${name}";`),
    "",
    "export const icons = {",
    ...entries.map((name) => `  ${name}: ${name}Cmp,`),
    "} as const;",
    "",
    "export type IconName = keyof typeof icons;",
    "",
  ].join("\n");
  writeFileSync(join(outDir, "index.ts"), barrel);

  console.log(`Generated ${entries.length} icon components in src/icons/`);
}

main();
