// Regenerates all of src/ from the raw SVG source of truth in assets/.
// Run via `npm run generate` (also runs automatically before `npm run build`).
//
// Every immediate subfolder of assets/ (e.g. assets/icons, assets/illustrations)
// is its own asset category: it gets a generated `Sezzy<Category>` component,
// a `<Category>Name` type, and its own registry under src/<category>/. A UI
// designer (or the Figma export pipeline) can create a brand-new category by
// just adding a new top-level folder under assets/ with SVGs in it — nothing
// here needs to change for that to pick it up.
import { transform } from "@svgr/core";
import { mkdirSync, writeFileSync, rmSync } from "node:fs";
import { join, relative, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { svgoConfig, readSvgFiles, discoverCategories } from "./lib/svg.mjs";

const rootDir = dirname(fileURLToPath(import.meta.url)) + "/..";
const assetsDir = join(rootDir, "assets");
const srcDir = join(rootDir, "src");

function componentTemplate({ componentName, typeName, registryImportPath, registryVarName, categoryLabel }) {
  return `// Auto-generated by scripts/generate.mjs — do not edit directly.
import type { SVGProps } from "react";
import { ${registryVarName}, type ${typeName} } from "${registryImportPath}";

export interface ${componentName}Props extends SVGProps<SVGSVGElement> {
  // \`string & {}\` keeps ${typeName} autocomplete/hints while still accepting
  // any plain string — callers with a dynamic name (e.g. from config/data)
  // don't need an \`as ${typeName}\` cast.
  name: ${typeName} | (string & {});
}

/**
 * Renders a sezzy-icons "${categoryLabel}" asset by name. Individual
 * components aren't exported, so this is the only way to render one.
 */
export function ${componentName}({ name, ...props }: ${componentName}Props) {
  const Component = ${registryVarName}[name as ${typeName}];
  if (!Component) return null;
  return <Component {...props} />;
}
`;
}

async function generateCategory(category) {
  const outDir = join(srcDir, category.folderName);
  mkdirSync(outDir, { recursive: true });

  const items = readSvgFiles(category.dir);

  for (const { filePath, componentName, svgCode } of items) {
    const tsx = await transform(
      svgCode,
      {
        typescript: true,
        icon: false,
        plugins: ["@svgr/plugin-svgo", "@svgr/plugin-jsx"],
        svgoConfig,
      },
      { componentName }
    );

    const relPath = relative(category.dir, filePath).replace(/\\/g, "/");
    const header = `// Auto-generated by scripts/generate.mjs from assets/${category.folderName}/${relPath}.\n// Do not edit directly — edit the source SVG and run \`npm run generate\`.\n`;
    writeFileSync(join(outDir, `${componentName}.tsx`), header + tsx);
  }

  const entries = items.map((i) => i.componentName);

  // Individual assets are intentionally NOT re-exported — Sezzy<Category>
  // (by name) is the only public way to render one. This barrel stays
  // internal to src/<category>/.
  const barrel = [
    "// Auto-generated by scripts/generate.mjs — do not edit directly.",
    ...entries.map((name) => `import ${name}Cmp from "./${name}";`),
    "",
    `export const ${category.folderName} = {`,
    ...entries.map((name) => `  ${name}: ${name}Cmp,`),
    "} as const;",
    "",
    `export type ${category.typeName} = keyof typeof ${category.folderName};`,
    "",
  ].join("\n");
  writeFileSync(join(outDir, "index.ts"), barrel);

  const componentTsx = componentTemplate({
    componentName: category.componentName,
    typeName: category.typeName,
    registryImportPath: `./${category.folderName}/index`,
    registryVarName: category.folderName,
    categoryLabel: category.folderName,
  });
  writeFileSync(join(srcDir, `${category.componentName}.tsx`), componentTsx);

  return entries.length;
}

async function main() {
  rmSync(srcDir, { recursive: true, force: true });
  mkdirSync(srcDir, { recursive: true });

  const categories = discoverCategories(assetsDir);
  const counts = [];
  for (const category of categories) {
    counts.push([category, await generateCategory(category)]);
  }

  const indexLines = [
    "// Auto-generated by scripts/generate.mjs — do not edit directly.",
    ...categories.flatMap((c) => [
      `export { ${c.componentName} } from "./${c.componentName}";`,
      `export type { ${c.componentName}Props } from "./${c.componentName}";`,
      `export type { ${c.typeName} } from "./${c.folderName}/index";`,
    ]),
    "",
  ].join("\n");
  writeFileSync(join(srcDir, "index.ts"), indexLines);

  for (const [category, count] of counts) {
    console.log(`Generated ${count} "${category.folderName}" assets as <${category.componentName}> in src/${category.folderName}/`);
  }
}

main();
