// Regenerates src/icons/**/*.tsx from the raw SVG source of truth in icons/.
// Run via `npm run generate` (also runs automatically before `npm run build`).
// Icons pushed here by the Figma export pipeline are picked up the same way.
import { transform } from "@svgr/core";
import { readdirSync, statSync, mkdirSync, writeFileSync, rmSync, readFileSync } from "node:fs";
import { join, relative, dirname, basename, extname } from "node:path";
import { fileURLToPath } from "node:url";

const rootDir = dirname(fileURLToPath(import.meta.url)) + "/..";
const sourceDir = join(rootDir, "icons");
const outDir = join(rootDir, "src", "icons");

// Figma's background-blur export wraps a <div> in a <foreignObject> as a
// browser fallback for backdrop-filter. It carries no visible content of its
// own (the real shapes render from sibling elements) and React/TS reject the
// bare `xmlns` attribute on the div, so it's stripped rather than special-cased.
const removeForeignObject = {
  name: "removeForeignObject",
  fn: () => ({
    element: {
      enter: (node, parentNode) => {
        if (node.name === "foreignObject" && "children" in parentNode) {
          parentNode.children = parentNode.children.filter((child) => child !== node);
        }
      },
    },
  }),
};

const svgoConfig = {
  plugins: [
    {
      name: "preset-default",
      params: {
        overrides: {
          // Several source SVGs rely on the viewBox for correct scaling; keep it.
          removeViewBox: false,
        },
      },
    },
    removeForeignObject,
  ],
};

function toPascalCase(name) {
  return name
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .trim()
    .split(" ")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

function walkSvgFiles(dir) {
  const results = [];
  for (const entry of readdirSync(dir)) {
    const fullPath = join(dir, entry);
    if (statSync(fullPath).isDirectory()) {
      results.push(...walkSvgFiles(fullPath));
    } else if (extname(entry) === ".svg") {
      results.push(fullPath);
    }
  }
  return results;
}

function componentNameFor(filePath) {
  const relPath = relative(sourceDir, filePath);
  const folder = dirname(relPath);
  const base = toPascalCase(basename(relPath, ".svg"));
  if (folder === ".") return base;
  const prefix = toPascalCase(folder);
  return `${prefix}${base}`;
}

async function main() {
  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(outDir, { recursive: true });

  const files = walkSvgFiles(sourceDir);
  const seen = new Map();
  const entries = [];

  for (const filePath of files) {
    const svgCode = readFileSync(filePath, "utf8");
    const componentName = componentNameFor(filePath);

    if (seen.has(componentName)) {
      throw new Error(
        `Duplicate icon component name "${componentName}" from "${filePath}" and "${seen.get(componentName)}". Rename one of the source SVGs.`
      );
    }
    seen.set(componentName, filePath);

    const tsx = await transform(
      svgCode,
      {
        typescript: true,
        icon: false,
        plugins: ["@svgr/plugin-svgo", "@svgr/plugin-jsx"],
        svgoConfig,
      },
      { componentName }
    );

    const header = `// Auto-generated by scripts/generate-icons.mjs from icons/${relative(sourceDir, filePath).replace(/\\/g, "/")}.\n// Do not edit directly — edit the source SVG and run \`npm run generate\`.\n`;
    writeFileSync(join(outDir, `${componentName}.tsx`), header + tsx);
    entries.push(componentName);
  }

  entries.sort();

  const barrel = [
    "// Auto-generated by scripts/generate-icons.mjs — do not edit directly.",
    ...entries.map((name) => `export { default as ${name} } from "./${name}";`),
    "",
    ...entries.map((name) => `import ${name}Cmp from "./${name}";`),
    "",
    "export const icons = {",
    ...entries.map((name) => `  ${name}: ${name}Cmp,`),
    "} as const;",
    "",
    "export type IconName = keyof typeof icons;",
    "",
  ].join("\n");
  writeFileSync(join(outDir, "index.ts"), barrel);

  console.log(`Generated ${entries.length} icon components in src/icons/`);
}

main();
